import { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSession } from '../../App';
import { simulateTrade } from '../lib/learning';
const money=(v?:number)=>typeof v==='number'&&Number.isFinite(v)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v):'Unavailable';
export default function Learn(){
 const {token,request}=useSession();const [account,setAccount]=useState<any>(null),[error,setError]=useState('');
 const [margin,setMargin]=useState(''),[leverage,setLeverage]=useState(''),[stop,setStop]=useState(''),[target,setTarget]=useState('');
 useEffect(()=>{let mounted=true;request('dashboard','GET',undefined,token).then(value=>{if(mounted)setAccount(value);}).catch(e=>{if(mounted)setError(e.message);});return()=>{mounted=false;};},[request,token]);
 const result=simulateTrade(Number(margin),Number(leverage),Number(stop),Number(target));
 return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.title}>Understand your trade</Text><Text style={styles.copy}>A practice calculator. No orders are sent and your account is unchanged.</Text>{account&&<Text style={styles.copy}>{account.account.name??'Selected account'} · {account.account.stage??'Active'} · Equity {money(account.risk.equity)}</Text>}{!!error&&<Text style={styles.warning}>{error} You can still explore the calculator.</Text>}
 {([['Margin to allocate ($)',margin,setMargin],['Leverage (x)',leverage,setLeverage],['Stop distance (%)',stop,setStop],['Target distance (%)',target,setTarget]] as const).map(([label,value,set])=><View key={label}><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} keyboardType="decimal-pad" value={value} onChangeText={set} style={styles.input} placeholder="Enter amount" placeholderTextColor="#82968b"/></View>)}
 <Text style={styles.copy}>Margin is the balance allocated to support the position. Leverage multiplies exposure. A $500 margin at 5x creates $2,500 of exposure. A 1% price move changes P&L by about $25.</Text>
 {result?<View style={styles.card}><Text style={styles.value}>Exposure {money(result.notional)}</Text><Text style={styles.copy}>Margin allocated: {money(Number(margin))}. Margin is not the same as risk at stop.</Text><Text style={styles.warning}>At stop: loss {money(result.loss)} ({result.marginReturnLoss.toFixed(1)}% of margin)</Text><Text style={styles.green}>At target: profit {money(result.profit)} ({result.marginReturnProfit.toFixed(1)}% of margin)</Text><Text style={styles.copy}>Equity after stop: {typeof account?.risk.equity==='number'?money(account.risk.equity-result.loss):'Unavailable'}</Text><Text style={styles.copy}>Equity after target: {typeof account?.risk.equity==='number'?money(account.risk.equity+result.profit):'Unavailable'}</Text>
 {account&&<>{(['dailyLoss','maxDrawdown'] as const).map(key=>{const room=account.rules[key].room;return <Text key={key} style={typeof room==='number'&&result.loss>=room?styles.warning:styles.copy}>{key==='dailyLoss'?'Daily loss':'Maximum drawdown'} room after stop: {typeof room==='number'?money(room-result.loss):'Unavailable'}{typeof room==='number'&&result.loss>=room?' · Would reach or cross the floor':''}</Text>;})}{typeof account.rules.profit.remaining==='number'&&<Text style={styles.copy}>Profit target remaining after win: {money(Math.max(0,account.rules.profit.remaining-result.profit))}</Text>}{typeof account.risk.available_balance==='number'&&Number(margin)>account.risk.available_balance&&<Text style={styles.warning}>Margin exceeds the available balance in this snapshot.</Text>}</>}
 {result.loss>=Number(margin)&&<Text style={styles.warning}>This stop implies losing at least the allocated margin. Liquidation can occur before your stop, depending on platform maintenance margin.</Text>}</View>:<Text style={styles.copy}>Enter positive amounts above to explore a scenario. Stop distance must be below 100%.</Text>}
 <Text style={styles.copy}>Stop loss requests an exit to limit losses. Take profit requests an exit at a profit target. Neither guarantees a fill at its trigger price.</Text><Text style={styles.small}>Simplified linear exposure model. Excludes fees, funding, slippage, liquidation and other positions. Account limits use the current selected account snapshot from MyFundedPerps. This is education, not a trade recommendation.</Text>
 </ScrollView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#07120e'},content:{padding:22,gap:18,paddingBottom:50},title:{color:'#f4f8f5',fontSize:28,fontWeight:'700'},copy:{color:'#b0c4b8',fontSize:16,lineHeight:24},label:{color:'#b0c4b8',marginBottom:8},input:{color:'#fff',backgroundColor:'#14271e',padding:16,borderRadius:12,fontSize:20},card:{backgroundColor:'#102219',padding:18,borderRadius:18,gap:14},value:{color:'#fff',fontSize:24,fontWeight:'600'},warning:{color:'#ffc19c',lineHeight:23},green:{color:'#2dcc98',lineHeight:23},small:{color:'#82968b',fontSize:13,lineHeight:20}});
