import { useEffect, useRef, useState } from 'react';
import { Alert, ScrollView, Text, TextInput, Pressable, StyleSheet, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useSession } from '../../App';
const money=(v:number)=>Number.isFinite(v)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v):'Unavailable';
export default function Protection(){
 const {positionId}=useLocalSearchParams<{positionId:string}>(),{request,token}=useSession();
 const [data,setData]=useState<any>(null),[tp,setTp]=useState(''),[sl,setSl]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const pending=useRef(false);
 const [closeFee,setCloseFee]=useState<number|undefined>(undefined);
 useEffect(()=>{let mounted=true;request('activity','GET',undefined,token).then(value=>{const fee=value.open?.find((p:{id:string})=>p.id===positionId)?.estimatedCloseFee;if(mounted&&typeof fee==='number'&&Number.isFinite(fee))setCloseFee(fee);}).catch(()=>{});return()=>{mounted=false;};},[request,token,positionId]);
 useEffect(()=>{let mounted=true;request('protection','POST',{positionId},token).then(value=>{if(!mounted)return;setData(value);const p=value.position;setTp(String(p.entry_price*(p.side==='long'?1.01:.99)));setSl(String(p.entry_price*(p.side==='long'?.995:1.005)));for(const o of value.orders){const price=o.trigger_price??o.limit_price??o.price;if(price!=null){if(/tp|take/i.test(o.group??o.exit_group??o.type??''))setTp(String(price));if(/sl|stop/i.test(o.group??o.exit_group??o.type??''))setSl(String(price));}}}).catch(e=>{if(mounted)setError(e.message);});return()=>{mounted=false;};},[request,token,positionId]);
 function impact(value:string){if(!data||!value.trim()||!Number.isFinite(Number(value))||Number(value)<=0)return 'Enter a positive price';const p=data.position,change=(Number(value)-p.entry_price)*(p.side==='long'?1:-1);return `${money(change*Math.abs(p.size))} · ${(change/p.entry_price*100).toFixed(2)}% price move from entry`;}
 async function review(){if(pending.current||!data)return;if(![tp,sl].every(v=>v.trim()&&Number.isFinite(Number(v))&&Number(v)>0)){setError('Enter positive TP and SL prices.');return;}pending.current=true;setBusy(true);setError('');try{const result=await request('protection/quote','POST',{positionId,takeProfitPrice:Number(tp),stopLossPrice:Number(sl)},token);Alert.alert('Confirm TP/SL edit',`Take profit ${money(Number(tp))}\n${impact(tp)}\n\nStop loss ${money(Number(sl))}\n${impact(sl)}\n\n${result.dryRun?'Dry run only. No exits will change.':'Replaces working TP/SL exits for the full position.'}`,[{text:'Cancel',style:'cancel'},{text:result.dryRun?'Validate':'Confirm edit',onPress:()=>void confirm(result.ticket.id)}]);}catch(e){setError(e instanceof Error?e.message:'Could not review exits.');}finally{pending.current=false;setBusy(false);}}
 async function confirm(ticketId:string){if(pending.current)return;pending.current=true;setBusy(true);try{const result=await request('protection/confirm','POST',{ticketId},token);setNotice(result.dryRun?'Dry run validated. Exits remain unchanged.':`Edit ${result.status}. Refresh Activity to check your position.`);}catch(e){setError(e instanceof Error?e.message:'Could not update exits. Check MyFundedPerps before retrying.');}finally{pending.current=false;setBusy(false);}}
 const position=data?.position;
 const estimate=(value:string)=>{const price=Number(value),entry=Number(position?.entry_price),size=Math.abs(Number(position?.size)),direction=position?.side==='long'?1:-1;if(!value.trim()||price<=0||!Number.isFinite(price)||!(entry>0)||!Number.isFinite(size))return null;const gross=(price-entry)*size*direction;return {move:(price-entry)/entry*100*direction,gross,net:closeFee===undefined?undefined:gross-closeFee};};
 const tpEstimate=estimate(tp),slEstimate=estimate(sl),ratio=tpEstimate&&slEstimate&&tpEstimate.gross>0&&slEstimate.gross<0?tpEstimate.gross/Math.abs(slEstimate.gross):undefined;
 const signedMoney=(v:number|undefined)=>v===undefined?'—':`${v>=0?'+':''}${money(v)}`;
 const metric=(label:string,value:string,color?:string)=><View key={label} style={styles.metric}><Text style={styles.small}>{label}</Text><Text style={[styles.metricValue,color?{color}:undefined]}>{value}</Text></View>;
 return <ScrollView showsVerticalScrollIndicator={false} style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
 <Text style={styles.eyebrow}>POSITION PROTECTION</Text><Text style={styles.title}>Edit {position?.symbol??'position'} TP/SL</Text><Text style={styles.small}>Review the estimated effect before replacing both exits as an OCO pair.</Text>
 {position&&<View style={styles.summary}><View style={styles.row}>{metric('Side',position.side.toUpperCase())}{metric('Entry',money(position.entry_price))}{metric('Current mark',money(data.markPrice))}</View><View style={styles.row}>{metric('Position size',String(position.size))}{metric('Est. close fee',closeFee===undefined?'Unavailable':money(closeFee))}{metric('Leverage',position.leverage?`${position.leverage}x`:'—')}</View></View>}
 {([['Take-profit',tp,setTp,tpEstimate],['Stop-loss',sl,setSl,slEstimate]] as const).map(([label,value,set,values])=><View key={label} style={[styles.leg,{borderColor:label==='Take-profit'?'#205c46':'#58332f'}]}><Text style={styles.label}>{label} price</Text><TextInput accessibilityLabel={`${label} price`} value={value} onChangeText={set} keyboardType="decimal-pad" style={styles.input} placeholder="Price" placeholderTextColor="#82968b"/><View style={styles.row}>{metric('Move vs entry',values?`${values.move>=0?'+':''}${values.move.toFixed(2)}%`:'—',values?values.move>=0?'#2dcc98':'#ff637e':undefined)}{metric('Gross P&L',signedMoney(values?.gross),values?values.gross>=0?'#2dcc98':'#ff637e':undefined)}{metric('After est. fee',signedMoney(values?.net),values?.net!==undefined?values.net>=0?'#2dcc98':'#ff637e':undefined)}</View></View>)}
 <View style={styles.ratio}><Text style={styles.small}>Estimated reward to risk</Text><Text style={styles.ratioValue}>{ratio===undefined?'—':`${ratio.toFixed(2)}x`}</Text></View>
 <Text style={styles.small}>Estimates exclude slippage and funding. After-fee P&L subtracts the current estimated close fee. A stop loss can also protect an existing profit.</Text>
 <Text style={styles.small}>Existing exits are loaded when available; otherwise the fields show proposed 1% take-profit and 0.5% stop-loss moves. Review checks prices against a fresh market quote.</Text>
 {!!error&&<Text accessibilityRole="alert" style={styles.error}>{error}</Text>}{!!notice&&<Text accessibilityRole="alert" style={styles.green}>{notice}</Text>}
 <View style={styles.row}><Pressable accessibilityRole="button" disabled={busy} onPress={()=>router.back()} style={styles.cancel}><Text style={styles.value}>Cancel</Text></Pressable><Pressable accessibilityRole="button" disabled={busy||!data||!tpEstimate||!slEstimate} onPress={()=>void review()} style={[styles.button,(busy||!data||!tpEstimate||!slEstimate)&&{opacity:.4}]}><Text style={styles.buttonText}>{busy?'Checking…':'Review TP/SL edit'}</Text></Pressable></View></ScrollView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#07120e'},content:{padding:18,gap:14,paddingBottom:50},eyebrow:{color:'#2dcc98',fontSize:12,fontWeight:'700',letterSpacing:2},title:{color:'#fff',fontSize:26,fontWeight:'700'},small:{color:'#82968b',fontSize:11,lineHeight:17},summary:{gap:8},row:{flexDirection:'row',gap:8},metric:{flex:1,minWidth:0,backgroundColor:'#122019',padding:10,borderRadius:12,gap:10},metricValue:{color:'#f4f8f5',fontSize:14,fontWeight:'700',fontVariant:['tabular-nums']},label:{color:'#a9bbb2',fontSize:15,fontWeight:'600'},leg:{padding:12,gap:12,borderWidth:1,borderRadius:18,backgroundColor:'#0b1711'},input:{backgroundColor:'#07120e',borderWidth:1,borderColor:'#284237',color:'#fff',padding:12,borderRadius:10,fontSize:21,fontWeight:'600'},ratio:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',padding:14,borderWidth:1,borderColor:'#284237',borderRadius:14},ratioValue:{color:'#eec85e',fontSize:24,fontWeight:'700'},green:{color:'#71e6b8',lineHeight:22},error:{color:'#ff9c9c',lineHeight:23},button:{flex:2,padding:16,borderRadius:14,backgroundColor:'#2dcc98',alignItems:'center',justifyContent:'center'},cancel:{flex:1,padding:16,borderRadius:14,borderWidth:1,borderColor:'#425048',alignItems:'center',justifyContent:'center'},value:{color:'#fff',fontSize:16,fontWeight:'600'},buttonText:{color:'#07120e',fontSize:15,fontWeight:'700'}});
