import { useEffect, useRef, useState } from 'react';
import { Alert, ScrollView, Text, TextInput, Pressable, StyleSheet, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { useSession } from '../../App';
const money=(v:number)=>Number.isFinite(v)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v):'Unavailable';
export default function Protection(){
 const {positionId}=useLocalSearchParams<{positionId:string}>(),{request,token}=useSession();
 const [data,setData]=useState<any>(null),[tp,setTp]=useState(''),[sl,setSl]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const pending=useRef(false);
 useEffect(()=>{let mounted=true;request('protection','POST',{positionId},token).then(value=>{if(!mounted)return;setData(value);for(const o of value.orders){const price=o.trigger_price??o.limit_price??o.price;if(price!=null){if((o.group??o.exit_group)==='tp')setTp(String(price));if((o.group??o.exit_group)==='sl')setSl(String(price));}}}).catch(e=>{if(mounted)setError(e.message);});return()=>{mounted=false;};},[request,token,positionId]);
 function impact(value:string){if(!data||!value.trim()||!Number.isFinite(Number(value))||Number(value)<=0)return 'Enter a positive price';const p=data.position,change=(Number(value)-p.entry_price)*(p.side==='long'?1:-1);return `${money(change*Math.abs(p.size))} · ${(change/p.entry_price*100).toFixed(2)}% price move from entry`;}
 async function review(){if(pending.current||!data)return;if(![tp,sl].every(v=>v.trim()&&Number.isFinite(Number(v))&&Number(v)>0)){setError('Enter positive TP and SL prices.');return;}pending.current=true;setBusy(true);setError('');try{const result=await request('protection/quote','POST',{positionId,takeProfitPrice:Number(tp),stopLossPrice:Number(sl)},token);Alert.alert('Confirm TP/SL edit',`Take profit ${money(Number(tp))}\n${impact(tp)}\n\nStop loss ${money(Number(sl))}\n${impact(sl)}\n\n${result.dryRun?'Dry run only. No exits will change.':'Replaces working TP/SL exits for the full position.'}`,[{text:'Cancel',style:'cancel'},{text:result.dryRun?'Validate':'Confirm edit',onPress:()=>void confirm(result.ticket.id)}]);}catch(e){setError(e instanceof Error?e.message:'Could not review exits.');}finally{pending.current=false;setBusy(false);}}
 async function confirm(ticketId:string){if(pending.current)return;pending.current=true;setBusy(true);try{const result=await request('protection/confirm','POST',{ticketId},token);setNotice(result.dryRun?'Dry run validated. Exits remain unchanged.':`Edit ${result.status}. Refresh Activity to check your position.`);}catch(e){setError(e instanceof Error?e.message:'Could not update exits. Check MyFundedPerps before retrying.');}finally{pending.current=false;setBusy(false);}}
 return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.title}>{data?.position.symbol??'Position'} TP/SL</Text>{data&&<Text style={styles.copy}>{data.position.side.toUpperCase()} · Size {data.position.size}\nEntry {money(data.position.entry_price)}\nCurrent market snapshot {money(data.markPrice)}</Text>}<Text style={styles.copy}>Enter trigger prices. Estimates show the full position’s gross P&L from entry, excluding fees, funding and slippage.</Text>{([['Take profit',tp,setTp],['Stop loss',sl,setSl]] as const).map(([label,value,set])=><View key={label}><Text style={styles.copy}>{label} price</Text><TextInput accessibilityLabel={`${label} price`} value={value} onChangeText={set} keyboardType="decimal-pad" style={styles.input} placeholder="Price" placeholderTextColor="#82968b"/><Text style={styles.green}>{impact(value)}</Text></View>)}<Text style={styles.copy}>A stop loss can protect an existing profit. Trigger prices are checked against a fresh market price when you review and confirm.</Text>{!!error&&<Text accessibilityRole="alert" style={styles.error}>{error}</Text>}{!!notice&&<Text style={styles.green}>{notice}</Text>}<Pressable accessibilityRole="button" disabled={busy||!data} onPress={()=>void review()} style={styles.button}><Text style={styles.value}>{busy?'Checking…':'Review TP/SL edit'}</Text></Pressable></ScrollView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#07120e'},content:{padding:22,gap:20,paddingBottom:50},title:{color:'#fff',fontSize:26,fontWeight:'700'},copy:{color:'#a9bbb2',lineHeight:24,fontSize:16},input:{backgroundColor:'#14271e',color:'#fff',padding:16,borderRadius:12,fontSize:20,marginVertical:12},green:{color:'#71e6b8',lineHeight:22},error:{color:'#ff9c9c',lineHeight:23},button:{padding:16,borderRadius:12,backgroundColor:'#24533e',alignItems:'center'},value:{color:'#fff',fontWeight:'600'}});
