import {afterEach,describe,it,expect,vi} from 'vitest';
import {MobileActivity,validateProtection} from '../src/mobile-activity.js';
import {MfpClient} from '../src/mfp.js';
import {SecretBox} from '../src/crypto.js';
import {loadConfig} from '../src/config.js';
const config=loadConfig({TELEGRAM_BOT_TOKEN:'test',DATABASE_URL:'postgres://localhost/test',ENCRYPTION_KEY:Buffer.alloc(32,1).toString('base64'),ALLOW_LIVE_TRADING:'true',DRY_RUN:'false'});
afterEach(()=>vi.restoreAllMocks());
function setup(){const auth={connection:vi.fn().mockResolvedValue({environment:'live',selected_account_id:'a',encrypted_api_key:new SecretBox(config.ENCRYPTION_KEY).encrypt('key')}),saveClose:vi.fn(),claimClose:vi.fn()};const position={id:'p',size:2,market_id:'m',side:'long',entry_price:100};vi.spyOn(MfpClient.prototype,'listOpenPositions').mockResolvedValue([position as never]);vi.spyOn(MfpClient.prototype,'listWorkingOrders').mockResolvedValue([]);vi.spyOn(MfpClient.prototype,'getQuote').mockResolvedValue({mid:110,bid:109,ask:111});return {auth,activity:new MobileActivity(auth as never,config)};}
describe('native protection',()=>{
 it('allows profitable stops relative to the current price',()=>{expect(()=>validateProtection({side:'long'},110,120,105)).not.toThrow();expect(()=>validateProtection({side:'short'},90,80,95)).not.toThrow();expect(()=>validateProtection({side:'long'},110,100,105)).toThrow();});
 it('rejects another account position',async()=>{const {activity}=setup();await expect(activity.quoteProtection('s',{positionId:'other',takeProfitPrice:120,stopLossPrice:105})).rejects.toThrow('no longer open');});
 it('claims once and uses a stable key',async()=>{const {auth,activity}=setup();const {ticket}=await activity.quoteProtection('s',{positionId:'p',takeProfitPrice:120,stopLossPrice:105});auth.claimClose.mockResolvedValueOnce(ticket).mockResolvedValue(undefined);const send=vi.spyOn(MfpClient.prototype,'replacePositionExits').mockResolvedValue({status:'pending'});await activity.confirmProtection('s',ticket.id);expect(send).toHaveBeenCalledWith(expect.anything(),[],120,105,ticket.id);await expect(activity.confirmProtection('s',ticket.id)).rejects.toThrow('already submitted');expect(send).toHaveBeenCalledTimes(1);});
 it('rejects changed exits or using an edit ticket to close',async()=>{const {auth,activity}=setup();const {ticket}=await activity.quoteProtection('s',{positionId:'p',takeProfitPrice:120,stopLossPrice:105});auth.claimClose.mockResolvedValue(ticket);vi.spyOn(MfpClient.prototype,'listWorkingOrders').mockResolvedValue([{id:'o',reduce_only:true,position_id:'p',group:'tp',size:2,price:125} as never]);await expect(activity.confirmProtection('s',ticket.id)).rejects.toThrow('exits changed');await expect(activity.confirmClose('s',ticket.id)).rejects.toThrow('not a close');});
 it('does not share positions outside the selected account or invent P&L',async()=>{const {activity}=setup();vi.spyOn(MfpClient.prototype,'listClosedPositions').mockResolvedValue([{id:'p'} as never]);await expect(activity.share('s','other')).rejects.toThrow('unavailable');await expect(activity.share('s','p')).rejects.toThrow('P&L is unavailable');});
});
