import {useState} from 'react';
import {Pressable,StyleSheet,Text,View} from 'react-native';
import {useMarketChart} from '../hooks/use-market-chart';
import {chartRange} from '../lib/chart-data';
const money=(n?:number)=>n!==undefined&&Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:n<10?5:2}).format(n):'Unavailable';
export default function MarketChart({provider,coin}:{provider:string;coin:string}){
 const [mode,setMode]=useState<'line'|'candles'>('line'),[interval,setInterval]=useState('5m'),[width,setWidth]=useState(0),[inspect,setInspect]=useState<number|null>(null);
 const data=useMarketChart(provider,coin,interval),bars=data.bars.slice(-60),range=chartRange(bars,mode==='candles'),height=190,pad=10,plotWidth=Math.max(1,width-20),step=plotWidth/Math.max(1,bars.length-1);
 const x=(i:number)=>pad+i*step,y=(price:number)=>pad+(range.high-price)/(range.high-range.low)*(height-2*pad);
 const chosen=inspect===null?null:bars[Math.min(inspect,bars.length-1)],color=bars.length&&bars.at(-1)!.close<bars[0].close?'#ff778c':'#2dcc98';
 function select(location:number){if(!bars.length)return;setInspect(Math.max(0,Math.min(bars.length-1,Math.round((location-pad)/step))));}
 return <View style={styles.card}><View style={styles.row}><Text style={styles.price}>{money(data.price)}</Text><Text style={styles.small}>{data.status}</Text></View>
 <View style={styles.row}>{(['line','candles'] as const).map(value=><Pressable key={value} accessibilityRole="button" accessibilityState={{selected:mode===value}} onPress={()=>{setMode(value);setInspect(null);}} style={[styles.option,mode===value&&styles.selected]}><Text style={styles.label}>{value==='line'?'Line':'Candles'}</Text></Pressable>)}</View>
 <View style={styles.row}>{['1m','5m','15m','30m','1h','4h'].map(value=><Pressable key={value} accessibilityRole="button" accessibilityState={{selected:interval===value}} onPress={()=>{setInterval(value);setInspect(null);}} style={[styles.frame,interval===value&&styles.selected]}><Text style={styles.small}>{value}</Text></Pressable>)}</View>
 <View style={{minHeight:62}}>{chosen?<><Text selectable style={styles.label}>{new Date(chosen.time).toLocaleString()}</Text><Text selectable style={styles.small}>{mode==='candles'?`O ${money(chosen.open)}  H ${money(chosen.high)}\nL ${money(chosen.low)}  C ${money(chosen.close)}`:`Close ${money(chosen.close)}`}</Text></>:<Text style={styles.small}>{bars.length?'Touch and drag to inspect price and time.':'Waiting for candle history from the market feed…'}</Text>}</View>
 <View onLayout={e=>setWidth(e.nativeEvent.layout.width)} style={{height}}>
 {[0,0.5,1].map(f=><View pointerEvents="none" key={f} style={{position:'absolute',top:pad+f*(height-2*pad),left:0,right:0,height:1,backgroundColor:'#284237'}}/>)}
 <View pointerEvents="none" style={StyleSheet.absoluteFill}>{width>0&&(mode==='candles'?bars.map((b,i)=>{const c=b.close>=b.open?'#2dcc98':'#ff778c',w=Math.max(2,Math.min(9,step*.65));return <View key={b.time}><View style={{position:'absolute',left:x(i),top:y(b.high),width:1,height:Math.max(1,y(b.low)-y(b.high)),backgroundColor:c}}/><View style={{position:'absolute',left:x(i)-w/2,top:y(Math.max(b.open,b.close)),width:w,height:Math.max(2,Math.abs(y(b.open)-y(b.close))),backgroundColor:c,borderRadius:1}}/></View>;}):bars.slice(1).map((b,i)=>{const prior=bars[i],dx=step,dy=y(b.close)-y(prior.close),length=Math.hypot(dx,dy);return <View key={b.time} style={{position:'absolute',left:(x(i)+x(i+1))/2-length/2,top:(y(prior.close)+y(b.close))/2-1,width:length,height:2,backgroundColor:color,transform:[{rotate:`${Math.atan2(dy,dx)}rad`}]}}/>;}))}
 {chosen&&<><View style={{position:'absolute',left:x(Math.min(inspect!,bars.length-1)),top:0,bottom:0,width:1,backgroundColor:'#f4f8f5'}}/><View style={{position:'absolute',top:y(chosen.close),left:0,right:0,height:1,backgroundColor:'#f4f8f5'}}/></>}
 </View><View style={StyleSheet.absoluteFill} accessible accessibilityLabel={`${mode} chart. ${bars.length} points. Latest ${money(data.price)}.`} onStartShouldSetResponder={()=>bars.length>0} onResponderGrant={e=>select(e.nativeEvent.locationX)} onResponderMove={e=>select(e.nativeEvent.locationX)} onResponderTerminationRequest={()=>false}/>
 </View><View style={styles.row}><Text style={styles.small}>{bars.length?new Date(bars[0].time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):''}</Text><Text style={styles.small}>{bars.length?new Date(bars.at(-1)!.time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):''}</Text></View>
 <Text style={styles.small}>Range {money(range.low)} to {money(range.high)} · {interval} candle closes</Text>
 {inspect!==null&&<Pressable accessibilityRole="button" onPress={()=>setInspect(null)}><Text style={styles.green}>Return to live view</Text></Pressable>}
 <View style={styles.book}><View><Text style={styles.small}>Best bid</Text><Text style={styles.green}>{money(data.bid)}</Text></View><View><Text style={styles.small}>Spread</Text><Text style={styles.label}>{data.bid!==undefined&&data.ask!==undefined?money(data.ask-data.bid):'Unavailable'}</Text></View><View><Text style={styles.small}>Best ask</Text><Text style={styles.red}>{money(data.ask)}</Text></View></View>
 </View>;
}
const styles=StyleSheet.create({card:{backgroundColor:'#102219',padding:16,borderRadius:20,gap:12},row:{flexDirection:'row',justifyContent:'space-between',gap:4,alignItems:'center'},price:{color:'#fff',fontSize:26,fontWeight:'600'},label:{color:'#f4f8f5',fontSize:14},small:{color:'#a9bbb2',fontSize:12,lineHeight:19},option:{padding:12,borderRadius:12,flex:1,alignItems:'center',backgroundColor:'#172e22'},frame:{paddingVertical:10,paddingHorizontal:6,borderRadius:8},selected:{backgroundColor:'#24533e'},book:{flexDirection:'row',justifyContent:'space-between',gap:8,paddingTop:12,borderTopWidth:1,borderTopColor:'#284237'},green:{color:'#71e6b8',paddingVertical:6},red:{color:'#ff778c',paddingVertical:6}});
