import {ReactNode,useEffect,useRef,useState} from 'react';
import {Pressable,StyleSheet,Text,View} from 'react-native';
import {useMarketChart} from '../hooks/use-market-chart';
import {useProtectionLines} from '../hooks/use-protection-lines';
import {chartRange} from '../lib/chart-data';
const money=(n?:number)=>n!==undefined&&Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:n<1?8:n<10?5:2}).format(n):'Unavailable';
export default function MarketChart({provider,coin,symbol,children,showProtection=false}:{provider:string;coin:string;symbol?:string;children?:ReactNode;showProtection?:boolean}){
 const [mode,setMode]=useState<'line'|'candles'>('line'),[interval,setInterval]=useState('5m'),[width,setWidth]=useState(0),[inspect,setInspect]=useState<number|null>(null);
 const [visibleCount,setVisibleCount]=useState(60),[offset,setOffset]=useState(0);
 const gesture=useRef<{x:number;offset:number;inspect:boolean;moved:boolean}|null>(null);
 const lastTap=useRef(0);
 const holdTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(holdTimer.current)clearTimeout(holdTimer.current);},[]);
 function endGesture(){if(holdTimer.current)clearTimeout(holdTimer.current);holdTimer.current=null;pinch.current=null;gesture.current=null;}
 const pinch=useRef<{distance:number;count:number}|null>(null);
 const protection=useProtectionLines(provider,coin,showProtection);
 const data=useMarketChart(provider,coin,interval),end=Math.max(Math.min(visibleCount,data.bars.length),data.bars.length-Math.min(offset,Math.max(0,data.bars.length-visibleCount))),bars=data.bars.slice(Math.max(0,end-visibleCount),end),baseRange=chartRange(bars,mode==='candles'),levelPrices=protection.lines.map(l=>l.price),low=Math.min(baseRange.low,...levelPrices),high=Math.max(baseRange.high,...levelPrices),range={low:low-(high-low)*.04,high:high+(high-low)*.04},height=220,pad=10,plotWidth=Math.max(1,width-20),step=plotWidth/Math.max(1,bars.length-1);
 const x=(i:number)=>pad+i*step,y=(price:number)=>pad+(range.high-price)/(range.high-range.low)*(height-2*pad);
 const chosen=inspect===null?null:bars[Math.min(inspect,bars.length-1)],color=bars.length&&bars.at(-1)!.close<bars[0].close?'#ff778c':'#2dcc98';
 function zoom(count:number){setVisibleCount(Math.max(12,Math.min(70,Math.round(count))));setInspect(null);}
 function select(location:number){if(!bars.length)return;setInspect(Math.max(0,Math.min(bars.length-1,Math.round((location-pad)/step))));}
 return <><View style={styles.card}>
 <View style={styles.row}>{(['line','candles'] as const).map(value=><Pressable key={value} accessibilityRole="button" accessibilityState={{selected:mode===value}} onPress={()=>{setMode(value);setInspect(null);}} style={[styles.option,mode===value&&styles.selected]}><Text style={styles.label}>{value==='line'?'Line':'Candles'}</Text></Pressable>)}</View>
 <Text style={styles.small}>{symbol??coin} · {coin}</Text><View style={styles.row}><Text style={styles.price}>{money(data.price)}</Text><Text style={styles.green}>{data.status}</Text></View>
 {mode==='candles'&&<View style={styles.row}>{['1m','5m','15m','30m','1h','4h'].map(value=><Pressable key={value} accessibilityRole="button" accessibilityState={{selected:interval===value}} onPress={()=>{setInterval(value);setOffset(0);setInspect(null);}} style={[styles.frame,interval===value&&styles.selected]}><Text style={styles.small}>{value}</Text></Pressable>)}</View>}
 {chosen&&<View>{chosen?<><Text selectable style={styles.label}>{new Date(chosen.time).toLocaleString()}</Text><Text selectable style={styles.small}>{mode==='candles'?`O ${money(chosen.open)}  H ${money(chosen.high)}\nL ${money(chosen.low)}  C ${money(chosen.close)}`:`Close ${money(chosen.close)}`}</Text></>:<Text style={styles.small}>{bars.length?'Touch and drag to inspect price and time.':'Waiting for candle history from the market feed…'}</Text>}</View>}
 <View onLayout={e=>setWidth(e.nativeEvent.layout.width)} style={{height}}>
 {[0,0.5,1].map(f=><View pointerEvents="none" key={f} style={{position:'absolute',top:pad+f*(height-2*pad),left:0,right:0,height:1,backgroundColor:'#284237'}}/>)}
 <View pointerEvents="none" style={StyleSheet.absoluteFill}>{width>0&&(mode==='candles'?bars.map((b,i)=>{const c=b.close>=b.open?'#2dcc98':'#ff778c',w=Math.max(2,Math.min(22,step*.65));return <View key={b.time}><View style={{position:'absolute',left:x(i),top:y(b.high),width:1,height:Math.max(1,y(b.low)-y(b.high)),backgroundColor:c}}/><View style={{position:'absolute',left:x(i)-w/2,top:y(Math.max(b.open,b.close)),width:w,height:Math.max(2,Math.abs(y(b.open)-y(b.close))),backgroundColor:c,borderRadius:1}}/></View>;}):bars.slice(1).map((b,i)=>{const prior=bars[i],dx=step,dy=y(b.close)-y(prior.close),length=Math.hypot(dx,dy);return <View key={b.time} style={{position:'absolute',left:(x(i)+x(i+1))/2-length/2,top:(y(prior.close)+y(b.close))/2-1,width:length,height:2,backgroundColor:color,transform:[{rotate:`${Math.atan2(dy,dx)}rad`}]}}/>;}))}
 {protection.lines.map(line=><View key={line.id} style={{position:'absolute',top:y(line.price),left:0,right:0,borderTopWidth:1,borderStyle:'dashed',borderColor:line.kind==='TP'?'#2dcc98':'#ff778c'}}><Text style={{position:'absolute',right:0,top:-18,backgroundColor:'#0b1912',paddingHorizontal:4,color:line.kind==='TP'?'#2dcc98':'#ff778c',fontSize:11,fontWeight:'700'}}>{line.kind} {money(line.price)}</Text></View>)}
 {chosen&&<><View style={{position:'absolute',left:x(Math.min(inspect!,bars.length-1)),top:0,bottom:0,width:1,backgroundColor:'#f4f8f5'}}/><View style={{position:'absolute',top:y(chosen.close),left:0,right:0,height:1,backgroundColor:'#f4f8f5'}}/></>}
 </View><View style={StyleSheet.absoluteFill} accessible accessibilityLabel={`Pinch to zoom, swipe to scroll, hold to inspect. ${mode} chart. ${bars.length} points. Latest ${money(data.price)}.`} onStartShouldSetResponder={()=>bars.length>0} onResponderGrant={e=>{endGesture();gesture.current={x:e.nativeEvent.locationX,offset,inspect:false,moved:false};const location=e.nativeEvent.locationX;holdTimer.current=setTimeout(()=>{if(gesture.current&&!pinch.current){gesture.current.inspect=true;select(location);}},350);}} onResponderMove={e=>{const touches=e.nativeEvent.touches;if(touches.length===2){if(holdTimer.current)clearTimeout(holdTimer.current);const distance=Math.hypot(touches[0].pageX-touches[1].pageX,touches[0].pageY-touches[1].pageY);if(!pinch.current&&distance>0)pinch.current={distance,count:visibleCount};if(pinch.current&&distance>0)zoom(pinch.current.count*pinch.current.distance/distance);}else if(!pinch.current&&gesture.current){const delta=e.nativeEvent.locationX-gesture.current.x;if(gesture.current.inspect)select(e.nativeEvent.locationX);else if(Math.abs(delta)>8){gesture.current.moved=true;if(holdTimer.current)clearTimeout(holdTimer.current);setInspect(null);setOffset(Math.max(0,Math.min(Math.max(0,data.bars.length-visibleCount),gesture.current.offset+Math.round(delta/step))));}}}} onResponderRelease={()=>{if(gesture.current&&!gesture.current.moved&&!gesture.current.inspect&&!pinch.current){const now=Date.now();if(now-lastTap.current<300){zoom(60);setOffset(0);lastTap.current=0;}else lastTap.current=now;}endGesture();}} onResponderTerminate={endGesture} onResponderTerminationRequest={()=>false}/>
 </View><View style={styles.row}><Text style={styles.small}>{bars.length?new Date(bars[0].time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):''}</Text><Text style={styles.small}>{bars.length?new Date(bars.at(-1)!.time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):''}</Text></View>
 <View style={styles.row}><Text style={styles.small}>Pinch to zoom · swipe to scroll</Text><Text style={styles.small}>{provider.toUpperCase()}</Text></View>
 {showProtection&&<View><Text style={styles.small}>{protection.status}</Text>{protection.lines.map(line=><Text key={line.id} style={{color:line.kind==='TP'?'#2dcc98':'#ff778c',fontSize:12}}>{line.kind==='TP'?'Take profit':'Stop loss'} · {money(line.price)}</Text>)}</View>}
 <Text style={styles.small}>Hold to inspect · double-tap to reset</Text>
 </View>{children}<View style={styles.bookCard}><Text style={styles.small}>ORDER BOOK · TOP LEVEL</Text><View style={styles.book}><View style={styles.bookColumn}><Text style={styles.small}>Best bid</Text><Text numberOfLines={1} adjustsFontSizeToFit style={styles.green}>{money(data.bid)}</Text><Text style={styles.small}>{data.bidSize!==undefined?`Size ${data.bidSize.toLocaleString()}`:'Waiting for book'}</Text></View><View style={styles.bookColumn}><Text style={styles.small}>Spread</Text><Text numberOfLines={1} adjustsFontSizeToFit style={styles.label}>{data.bid!==undefined&&data.ask!==undefined?money(data.ask-data.bid):'Unavailable'}</Text><Text style={styles.small}>{data.bid!==undefined&&data.ask!==undefined?`${((data.ask-data.bid)/((data.ask+data.bid)/2)*100).toFixed(4)}%`:''}</Text></View><View style={styles.bookColumn}><Text style={styles.small}>Best ask</Text><Text numberOfLines={1} adjustsFontSizeToFit style={styles.red}>{money(data.ask)}</Text><Text style={styles.small}>{data.askSize!==undefined?`Size ${data.askSize.toLocaleString()}`:'Waiting for book'}</Text></View></View><View accessibilityLabel="Relative size at the best bid and best ask" style={{height:5,borderRadius:3,overflow:'hidden',flexDirection:'row'}}><View style={{flex:data.bidSize!==undefined&&data.askSize!==undefined&&data.bidSize+data.askSize>0?data.bidSize/(data.bidSize+data.askSize):.5,backgroundColor:'#2dcc98'}}/><View style={{flex:data.bidSize!==undefined&&data.askSize!==undefined&&data.bidSize+data.askSize>0?data.askSize/(data.bidSize+data.askSize):.5,backgroundColor:'#ff778c'}}/></View></View>
 </>;
}
const styles=StyleSheet.create({card:{backgroundColor:'#0b1912',padding:18,borderRadius:22,gap:14,borderWidth:1,borderColor:'#284237'},row:{flexDirection:'row',justifyContent:'space-between',gap:4,alignItems:'center'},price:{color:'#fff',fontSize:26,fontWeight:'600'},label:{color:'#f4f8f5',fontSize:14},small:{color:'#a9bbb2',fontSize:12,lineHeight:19},option:{padding:12,borderRadius:12,flex:1,alignItems:'center',backgroundColor:'#172e22'},frame:{paddingVertical:10,paddingHorizontal:6,borderRadius:8},selected:{backgroundColor:'#24533e'},bookCard:{padding:16,borderRadius:20,backgroundColor:'#0b1912',gap:10,borderWidth:1,borderColor:'#284237'},bookColumn:{flex:1,minWidth:0,alignItems:'center'},book:{flexDirection:'row',justifyContent:'space-between',gap:8,paddingTop:12,borderTopWidth:1,borderTopColor:'#284237'},green:{color:'#71e6b8',paddingVertical:6},red:{color:'#ff778c',paddingVertical:6}});
