import PulseNotifications from './PulseNotifications';
import { Link } from 'expo-router';
import { useIsFocused } from 'expo-router/react-navigation';
import AccountOnboarding from './AccountOnboarding';
import { useEffect, useState } from 'react';
import { Alert, Linking, Pressable, ScrollView, Text, TextInput, View, StyleSheet } from 'react-native';
import { useSession } from '../../App';
export default function Settings(){
 const focused=useIsFocused();const {user,token,request,busy,leave,error}=useSession();const [mode,setMode]=useState('off'),[max,setMax]=useState(''),[percent,setPercent]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[ready,setReady]=useState(false),[quickEnabled,setQuickEnabled]=useState(false),[amounts,setAmounts]=useState(['10','50','100']);
 useEffect(()=>{if(!focused)return;let mounted=true;request('guards','GET',undefined,token).then(value=>{if(mounted){setQuickEnabled(value.quickTradeEnabled===true);setAmounts((value.quickAmounts??[10,50,100]).map(String));setMode(value.mode);setMax(value.maxRiskUsd==null?'':String(value.maxRiskUsd));setPercent(value.lossRoomPercent==null?'':String(value.lossRoomPercent));setReady(true);}}).catch(e=>{if(mounted)setNotice(e.message);}).finally(()=>{if(mounted)setLoading(false);});return()=>{mounted=false;};},[request,token,focused]);
 async function save(){if(saving)return;if([max,percent,...amounts].some(v=>v.trim()&&(!Number.isFinite(Number(v))||Number(v)<=0))){setNotice('Enter positive numeric limits or leave them blank.');return;}setSaving(true);try{await request('guards','POST',{mode,quickTradeEnabled:quickEnabled,quickAmounts:amounts.map(Number),maxRiskUsd:max.trim()?Number(max):null,lossRoomPercent:percent.trim()?Number(percent):null},token);setNotice('Your trading preferences are saved.');}catch(e){setNotice(e instanceof Error?e.message:'Could not save.');}finally{setSaving(false);}}
 return <ScrollView showsVerticalScrollIndicator={false} showsHorizontalScrollIndicator={false} style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
 <Text style={styles.heading}>Settings</Text><Link href="/learn" asChild><Pressable accessibilityRole="button" style={{padding:18,borderRadius:16,backgroundColor:'#173a2b',borderWidth:1,borderColor:'#32664d',gap:6}}><Text style={{color:'#f4f8f5',fontSize:18,fontWeight:'700'}}>Learn with your account →</Text><Text style={styles.small}>Explore margin, leverage, stops and targets in a practice calculator.</Text></Pressable></Link><Text style={styles.heading}>Personal guardrails</Text><Text style={styles.copy}>Off by default. Choose your own limits. MyFundedPerps account rules still apply to every order.</Text>
 <View style={styles.row}>{(['off','warn','enforce'] as const).map(value=><Pressable key={value} accessibilityRole="button" accessibilityState={{selected:mode===value}} disabled={!ready||saving} style={[styles.option,mode===value&&styles.selected]} onPress={()=>setMode(value)}><Text style={styles.value}>{value==='off'?'Off':value==='warn'?'Warn me':'Enforce'}</Text></Pressable>)}</View>
 <Text style={styles.copy}>{mode==='off'?'Guardian adds no personal risk limit.':mode==='warn'?'Show warnings and allow you to decide.':'Block new trades that exceed your chosen limits. Position closing stays available.'}</Text>
 <Text style={styles.copy}>Maximum risk per trade ($), optional</Text><TextInput editable={ready&&!saving} accessibilityLabel="Maximum risk per trade" keyboardType="decimal-pad" value={max} onChangeText={setMax} placeholder="No personal limit" placeholderTextColor="#82968b" style={styles.input}/>
 <Text style={styles.copy}>Remaining loss room per trade (%), optional</Text><TextInput editable={ready&&!saving} accessibilityLabel="Loss room percentage" keyboardType="decimal-pad" value={percent} onChangeText={setPercent} placeholder="Choose 1 to 100" placeholderTextColor="#82968b" style={styles.input}/>
 <Text style={styles.small}>Uses the smaller available daily or maximum loss room. Limits cover the proposed trade risk at stop, excluding fees, slippage and other open risk. Settings apply across your linked accounts.</Text>
 <Text style={styles.heading}>One-tap trading</Text><Text style={styles.copy}>Choose three risk-at-stop amounts. After enabling, tapping one of these buttons in Trade immediately submits a market order with your selected direction, leverage, stop distance and reward/risk. There is no final confirmation. Fees and slippage can add to losses.</Text>
 <View style={styles.row}>{amounts.map((amount,i)=><TextInput key={i} accessibilityLabel={`Quick risk amount ${i+1}`} editable={ready&&!saving} value={amount} onChangeText={text=>setAmounts(current=>current.map((v,j)=>j===i?text:v))} keyboardType="decimal-pad" style={[styles.input,{flex:1,minWidth:0}]} />)}</View>
 <Pressable accessibilityRole="button" disabled={!ready||saving} style={styles.option} onPress={()=>quickEnabled?setQuickEnabled(false):Alert.alert('Enable immediate trading?','A quick-risk tap sends an order without another confirmation. Your enforced guardrails still apply. Warn mode displays warnings after submission.',[{text:'Cancel',style:'cancel'},{text:'Enable',onPress:()=>setQuickEnabled(true)}])}><Text style={styles.value}>{quickEnabled?'Enabled · tap to turn off':'Off · tap to enable'}</Text></Pressable>
 <Pressable accessibilityRole="button" disabled={!ready||saving||loading} onPress={()=>void save()} style={styles.option}><Text style={styles.link}>{loading?'Loading…':saving?'Saving…':'Save trading preferences'}</Text></Pressable>{!!notice&&<Text accessibilityRole="alert" style={styles.copy}>{notice}</Text>}
 <PulseNotifications/><AccountOnboarding token={token} request={request} showDashboard={false}/><Text style={styles.copy}>Signed in with {user.provider==='apple'?'Apple':'Google'}.</Text>
 <Text style={styles.heading}>Help & privacy</Text>{(['support','privacy'] as const).map(page=><Pressable key={page} accessibilityRole="link" style={styles.option} onPress={()=>void Linking.openURL(`https://fundedguardingbot-production.up.railway.app/${page}`).catch(()=>Alert.alert('Could not open page','Please try again when you have an internet connection.'))}><Text style={styles.link}>{page==='support'?'Support ↗':'Privacy Policy ↗'}</Text></Pressable>)}
 <Pressable accessibilityRole="button" disabled={busy} onPress={()=>void leave()}><Text style={styles.link}>Sign out</Text></Pressable>
 <Pressable accessibilityRole="button" disabled={busy} onPress={()=>Alert.alert('Delete Guardian account?','This removes your native login, saved API key and sessions. It does not close your MyFundedPerps positions.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>void leave(true)}])}><Text style={styles.error}>Delete Guardian account</Text></Pressable>{!!error&&<Text style={styles.error}>{error}</Text>}
 </ScrollView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#07120e'},content:{padding:24,gap:18,paddingBottom:50},heading:{color:'#fff',fontSize:25,fontWeight:'700'},copy:{color:'#a9bbb2',fontSize:16,lineHeight:24},small:{color:'#82968b',fontSize:13,lineHeight:20},link:{color:'#2dcc98',paddingVertical:12,fontSize:17},error:{color:'#ff9c9c',paddingVertical:12,fontSize:16},row:{flexDirection:'row',gap:8},option:{backgroundColor:'#14271e',borderRadius:12,padding:12},selected:{backgroundColor:'#24533e'},value:{color:'#fff'},input:{color:'#fff',backgroundColor:'#14271e',borderRadius:12,padding:16,fontSize:20}});
