import {useEffect,useState} from 'react';
import {Linking,Pressable,Switch,Text,View} from 'react-native';
import {storedNotificationPreferences,syncNotificationRegistration,saveNotificationPreferences} from '../lib/notification-registration';
import {NotificationPreferences} from '../lib/notification-preferences';
import {useSession} from '../../App';
export default function PulseNotifications(){
 const {request,token,user}=useSession();const [prefs,setPrefs]=useState({news:false,alerts:false,digest:false}),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{let active=true;async function load(){let cached:NotificationPreferences|null=null;try{cached=await storedNotificationPreferences(user.id);if(active&&cached){setPrefs(cached);}const p=await syncNotificationRegistration(user.id,token,request);if(active){setPrefs(p);setReady(true);}}catch(e){if(active){setReady(!!cached);setNotice(e instanceof Error?e.message:'Could not load notification preferences.');}}}void load();return()=>{active=false;};},[request,token,user.id]);
 async function save(next:NotificationPreferences=prefs){setBusy(true);setPrefs(next);setNotice('');try{await saveNotificationPreferences(user.id,token,request,next);setNotice('Notification settings saved.');}catch(e){setNotice(e instanceof Error?e.message:'Choices saved on this device; sync will retry when you reopen the app.');}finally{setBusy(false);}}
 async function retry(){setBusy(true);try{const p=await syncNotificationRegistration(user.id,token,request);setPrefs(p);setReady(true);setNotice('Notification settings loaded.');}catch(e){setNotice(e instanceof Error?e.message:'Could not load notification settings.');}finally{setBusy(false);}}
 return <View style={{gap:14,padding:18,borderRadius:16,backgroundColor:'#14271e'}}><Text style={{color:'#fff',fontSize:23,fontWeight:'700'}}>Pulse notifications</Text><Text style={{color:'#a9bbb2',lineHeight:22}}>Changes save automatically. News is limited to one every 30 minutes. The daily digest arrives around 8 AM Eastern.</Text>{(['alerts','news','digest'] as const).map(kind=><View key={kind} style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><Text style={{color:'#fff',fontSize:16}}>{kind==='alerts'?'Market moves':kind==='news'?'News headlines':'Daily digest'}</Text><Switch accessibilityLabel={kind} disabled={!ready||busy} value={prefs[kind]} onValueChange={value=>void save({...prefs,[kind]:value})}/></View>)}<Pressable accessibilityRole="button" disabled={busy} onPress={()=>void (ready?save():retry())} style={{padding:14,borderRadius:12,backgroundColor:'#24533e'}}><Text style={{color:'#2dcc98',fontWeight:'700'}}>{busy?'Saving…':ready?'Sync notifications':'Retry loading notifications'}</Text></Pressable>{!!notice&&<Text accessibilityRole="alert" style={{color:'#a9bbb2'}}>{notice}</Text>}<Pressable accessibilityRole="button" onPress={()=>void Linking.openSettings()}><Text style={{color:'#2dcc98'}}>Open iPhone notification settings</Text></Pressable></View>;
}
