import * as SecureStore from 'expo-secure-store';
import MarketLogo from '../../components/market-logo';
import { router } from 'expo-router';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, AppState, FlatList, RefreshControl, StyleSheet, Text, TextInput, Pressable, ScrollView, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useIsFocused } from 'expo-router/react-navigation';
import { useSession } from '../../../App';
type Market={id:string;symbol:string;coin:string;provider:string;maxLeverage?:number;category?:string};
type Stat={price?:number;change?:number;kind?:string;openInterest?:number;volume?:number};
const finite=(v:unknown)=>v!=null&&Number.isFinite(Number(v))?Number(v):undefined;
export default function Markets(){
 const {request,token,user}=useSession(),focused=useIsFocused();
 const [view,setView]=useState<'list'|'heatmap'>('heatmap');
 const [markets,setMarkets]=useState<Market[]|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState('Connecting'),[feed,setFeed]=useState<Record<string,Stat>>({}),[sort,setSort]=useState<'oi'|'change'|'name'>('oi');
 const [filter,setFilter]=useState('all'),[favorites,setFavorites]=useState<string[]>([]),[favoritesReady,setFavoritesReady]=useState(false),[width,setWidth]=useState(0);const favoriteRef=useRef<string[]>([]);const favoriteKey=`guardian-markets-${user.id}`;
 useEffect(()=>{let mounted=true;SecureStore.getItemAsync(favoriteKey).then(raw=>{if(!mounted)return;let items:string[]=[];try{const value=JSON.parse(raw??'[]');if(Array.isArray(value))items=value.filter(v=>typeof v==='string');}catch{}favoriteRef.current=items;setFavorites(items);}).catch(()=>{}).finally(()=>{if(mounted)setFavoritesReady(true);});return()=>{mounted=false;};},[favoriteKey]);
 async function toggleFavorite(id:string){if(!favoritesReady)return;const previous=favoriteRef.current,next=previous.includes(id)?previous.filter(v=>v!==id):[...previous,id];favoriteRef.current=next;setFavorites(next);try{await SecureStore.setItemAsync(favoriteKey,JSON.stringify(next));}catch{setError('Could not save favorites on this device.');}}
 function category(m:Market){const supplied=m.category?.toLowerCase()??'',name=m.symbol.toUpperCase();if(supplied.includes('forex')||supplied==='fx')return 'fx';if(supplied.includes('commod'))return 'commodities';if(supplied.includes('stock')||supplied.includes('indice')||supplied.includes('equity'))return 'other';if(/^(GOLD|SILVER|XAU|XAG|CL|WTI|BRENT|OIL)/.test(name))return 'commodities';if(/^(EUR|GBP|JPY|AUD|CAD|CHF|NZD)$/.test(name)||/^(EUR|GBP|USD|JPY|AUD|CAD|CHF|NZD)[/_-]?(EUR|GBP|USD|JPY|AUD|CAD|CHF|NZD)$/.test(name))return 'fx';if(/^(SP500|SPCX|XYZ100|NAS100|SKHX|SNDK|NVDA|SOXL|CRCL|MU)$/.test(name))return 'other';return 'crypto';}
 const load=useCallback(async()=>{setBusy(true);try{setMarkets((await request('markets','GET',undefined,token)).markets);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load markets.');}finally{setBusy(false);}},[request,token]);
 // Asynchronous market loading updates the screen after the request resolves.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{
  if(!focused||!markets?.length)return;
  let stopped=false,socket:WebSocket|null=null,retry:ReturnType<typeof setTimeout>|undefined,flush:ReturnType<typeof setTimeout>|undefined;
  const latest:Record<string,Stat>={};
  function connect(){
   if(stopped||AppState.currentState==='background')return;
   setStatus('Connecting');socket=new WebSocket('wss://api-stream.myfundedperpetuals.com/v1/market-data');
   socket.onopen=()=>{let id=100;const groups=new Map<string,string[]>();for(const m of markets!){const symbols=groups.get(m.provider)||[];if(!symbols.includes(m.coin))symbols.push(m.coin);groups.set(m.provider,symbols);}for(const [provider,symbols]of groups)for(let i=0;i<symbols.length;i+=32)for(const channel of ['ticks','marketStats'])socket?.send(JSON.stringify({op:'sub',id:id++,channel,payload:{symbols:symbols.slice(i,i+32),providers:[provider]}}));};
   socket.onmessage=message=>{try{const frame=JSON.parse(String(message.data));if(frame.op==='sub_ok')setStatus('Live');if(frame.op==='sub_err'||frame.op==='err')setStatus('Partial feed');for(const raw of frame.events||[]){const event=raw.tick||raw.marketStats||raw;if(!event.provider||!event.symbol)continue;const key=`${String(event.provider).toLowerCase()}|${String(event.symbol).toUpperCase()}`,stat=latest[key]||{};
    if(event.price!=null){const rank:Record<string,number>={last:1,mid:2,mark:3};if(!stat.kind||(rank[event.kind]||0)>=(rank[stat.kind]||0)){stat.price=finite(event.price);stat.kind=event.kind;}}
    if(event.change24hPct!==undefined)stat.change=finite(event.change24hPct);if(event.openInterestUsd!==undefined)stat.openInterest=finite(event.openInterestUsd);if(event.dayNtlVlm!==undefined)stat.volume=finite(event.dayNtlVlm);if(stat.price===undefined&&event.markPx!=null)stat.price=finite(event.markPx);latest[key]=stat;}
    if(!flush)flush=setTimeout(()=>{if(!stopped)setFeed({...latest});flush=undefined;},500);
   }catch{/* Ignore malformed public feed frames. */}};
   socket.onclose=()=>{socket=null;if(!stopped){setStatus('Reconnecting');retry=setTimeout(connect,3000);}};socket.onerror=()=>setStatus('Feed unavailable');
  }
  connect();const listener=AppState.addEventListener('change',state=>{if(state==='active'){if(!socket)connect();}else{if(retry)clearTimeout(retry);if(socket){socket.onclose=null;socket.close();socket=null;}setStatus('Paused');}});
  return()=>{stopped=true;listener.remove();if(retry)clearTimeout(retry);if(flush)clearTimeout(flush);socket?.close();};
 },[markets,focused]);
 const key=(m:Market)=>`${m.provider.toLowerCase()}|${m.coin.toUpperCase()}`;
 const filtered=(markets??[]).filter(m=>`${m.symbol} ${m.coin} ${m.provider}`.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='favorites'&&favorites.includes(m.id)||filter===category(m))).sort((a,b)=>sort==='name'?a.symbol.localeCompare(b.symbol):(sort==='oi'?(feed[key(b)]?.openInterest??-1)-(feed[key(a)]?.openInterest??-1):(feed[key(b)]?.change??-Infinity)-(feed[key(a)]?.change??-Infinity))||a.id.localeCompare(b.id));
 const featured=sort==='oi'?filtered.slice(0,3):[];const rest=featured.length===3?filtered.slice(3):filtered;const columns=width>=350?4:3;const rows:Market[][]=[];for(let i=0;i<rest.length;i+=columns)rows.push(rest.slice(i,i+columns));
 const compact=(v?:number)=>v===undefined?'Unavailable':new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(v);
 function tileColor(change?:number){if(change===undefined)return '#172a21';const amount=Math.min(1,Math.abs(change)/8);return change>=0?`rgb(${Math.round(18+amount*10)},${Math.round(50+amount*62)},${Math.round(39+amount*40)})`:`rgb(${Math.round(52+amount*75)},${Math.round(32+amount*7)},${Math.round(38+amount*18)})`;}
 const price=(v?:number)=>v===undefined?'Waiting for price':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:v<1?8:v<10?5:2}).format(v);
 const change=(v?:number)=>v===undefined?'Waiting':`${v>=0?'+':''}${v.toFixed(2)}%`;
 const tone=(v?:number)=>v===undefined?'#95aa9e':v>=0?'#71e6b8':'#ff9c9c';
 function open(m:Market){router.push({pathname:'/trade',params:{marketId:m.id}});}
 function tile(m:Market,size:'large'|'medium'|'small'|'tall'='small'){const stat=feed[key(m)]??{};return <Pressable key={m.id} accessibilityRole="button" accessibilityLabel={`${m.symbol}, ${m.provider}, ${change(stat.change)}, open chart`} onPress={()=>open(m)} style={[styles.tile,{backgroundColor:tileColor(stat.change),minHeight:size==='large'?280:size==='medium'?132:size==='tall'?206:146}]}><Pressable accessibilityRole="button" accessibilityLabel={`${favorites.includes(m.id)?'Remove':'Add'} ${m.symbol} ${favorites.includes(m.id)?'from':'to'} favorites`} disabled={!favoritesReady} hitSlop={4} onPress={e=>{e.stopPropagation();void toggleFavorite(m.id);}} style={styles.star}><Text style={{color:favorites.includes(m.id)?'#2dcc98':'#82968b',fontSize:23}}>★</Text></Pressable><MarketLogo symbol={m.symbol} size={size==='large'?50:size==='medium'?32:28}/><Text style={[styles.tileSymbol,{fontSize:size==='large'?30:size==='medium'?22:16}]} numberOfLines={1} adjustsFontSizeToFit minimumFontScale={.55}>{m.symbol}</Text><Text style={[styles.tileChange,{color:tone(stat.change),fontSize:size==='large'?22:14}]} numberOfLines={1} adjustsFontSizeToFit>{change(stat.change)}</Text><Text style={styles.oi} numberOfLines={1} adjustsFontSizeToFit>{stat.openInterest!==undefined?`OI $${compact(stat.openInterest)}`:'OI unavailable'}</Text></Pressable>;}
 const header=<View style={{gap:18}}><View style={styles.header}><View><Text style={styles.eyebrow}>LIVE DISCOVERY</Text><Text style={styles.heading}>Markets</Text></View><Text style={styles.status}>{status==='Live'?'● LIVE':status}</Text></View><View style={styles.summary}>{[['Available markets',markets?.length??0],['Live prices',(markets??[]).filter(m=>feed[key(m)]?.price!==undefined).length],['Providers',new Set((markets??[]).map(m=>m.provider)).size]].map(([label,value])=><View key={label} style={styles.summaryItem}><Text style={styles.copy}>{label}</Text><Text style={styles.summaryValue}>{value}</Text></View>)}</View><TextInput accessibilityLabel="Search markets" value={query} onChangeText={setQuery} placeholder="Search BTC, ETH, EUR…" placeholderTextColor="#82968b" style={styles.search} autoCorrect={false}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{[['all','All'],['favorites','★ Favorites'],['crypto','Crypto'],['fx','FX'],['commodities','Commodities'],['other','Other']].map(([value,label])=><Pressable key={value} accessibilityRole="button" accessibilityState={{selected:filter===value}} onPress={()=>setFilter(value)} style={[styles.filter,filter===value&&styles.activeFilter]}><Text style={[styles.label,filter===value&&{color:'#07120e'}]}>{label}</Text></Pressable>)}</ScrollView><View style={styles.header}><Text style={styles.copy}>MARKET OVERVIEW · 24H</Text><Pressable accessibilityRole="button" accessibilityLabel="Change market sorting" onPress={()=>setSort(sort==='oi'?'change':sort==='change'?'name':'oi')} style={styles.filter}><Text style={styles.label}>{sort==='oi'?'Open interest ↕':sort==='change'?'24h change ↕':'Name A–Z'}</Text></Pressable></View><View style={styles.header}><Pressable accessibilityRole="button" onPress={()=>setView(view==='heatmap'?'list':'heatmap')} style={{paddingVertical:10}}><Text style={styles.label}>{view==='heatmap'?'List view':'Heatmap view'}</Text></Pressable><View style={{flexDirection:'row',alignItems:'center',gap:6}}><Text style={styles.oi}>Declining</Text><View style={{width:18,height:5,borderRadius:3,backgroundColor:'#80414c'}}/><View style={{width:18,height:5,borderRadius:3,backgroundColor:'#1e805a'}}/><Text style={styles.oi}>Advancing</Text></View></View>{!!error&&<Text accessibilityRole="alert" style={styles.error}>{error}</Text>}{busy&&!markets&&<ActivityIndicator color="#2dcc98"/>}{view==='heatmap'&&featured.length===3&&<View style={styles.featured}><View style={{flex:1}}>{tile(featured[0],'large')}</View><View style={{flex:1,gap:10}}>{tile(featured[1],'medium')}{tile(featured[2],'medium')}</View></View>}</View>;
 return <SafeAreaView style={styles.page} edges={['top']} onLayout={e=>setWidth(e.nativeEvent.layout.width)}>{view==='heatmap'?<FlatList showsVerticalScrollIndicator={false} data={rows} keyExtractor={row=>row.map(m=>m.id).join(',')} contentContainerStyle={styles.list} ListHeaderComponent={header} refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>void load()} tintColor="#2dcc98"/>} ListEmptyComponent={featured.length===3?null:<Text style={styles.copy}>No matching markets.</Text>} ListFooterComponent={<Text style={[styles.copy,{textAlign:'center',paddingVertical:18}]}>Ranked by {sort==='oi'?'open interest':sort==='change'?'24h change':'name'}. Tap a market to chart and trade.</Text>} renderItem={({item:row,index})=><View style={styles.row}>{row.map(m=>tile(m,index===0&&featured.length===3?'tall':'small'))}{Array.from({length:columns-row.length},(_,i)=><View key={`space-${i}`} style={{flex:1}}/>)}</View>}/>:<FlatList showsVerticalScrollIndicator={false} data={filtered} keyExtractor={m=>m.id} contentContainerStyle={styles.list} ListHeaderComponent={header} refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>void load()} tintColor="#2dcc98"/>} ListEmptyComponent={<Text style={styles.copy}>No matching markets.</Text>} renderItem={({item})=>{const stat=feed[key(item)]??{};return <Pressable accessibilityRole="button" onPress={()=>open(item)} style={styles.marketRow}><MarketLogo symbol={item.symbol}/><View style={{flex:1}}><Text style={styles.symbol}>{item.symbol}</Text><Text style={styles.copy}>{item.provider}</Text></View><View style={styles.quote}><Text style={styles.price}>{price(stat.price)}</Text><Text style={{color:tone(stat.change)}}>{change(stat.change)}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={`Toggle ${item.symbol} favorite`} onPress={e=>{e.stopPropagation();void toggleFavorite(item.id);}} style={{padding:10}}><Text style={{color:favorites.includes(item.id)?'#2dcc98':'#82968b',fontSize:22}}>★</Text></Pressable></Pressable>;}}/>}</SafeAreaView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#07120e'},list:{padding:16,paddingBottom:28,gap:10},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:8},eyebrow:{color:'#2dcc98',fontSize:12,fontWeight:'700',letterSpacing:2,marginBottom:10},heading:{fontSize:34,fontWeight:'700',color:'#f4f8f5'},status:{color:'#2dcc98',fontSize:12,borderWidth:1,borderColor:'#32664d',borderRadius:24,padding:12},summary:{flexDirection:'row',backgroundColor:'#102219',padding:16,borderRadius:22,borderWidth:1,borderColor:'#284237'},summaryItem:{flex:1,gap:12},summaryValue:{fontSize:24,fontWeight:'700',color:'#f4f8f5'},search:{padding:18,color:'#f4f8f5',backgroundColor:'#0b1912',borderWidth:1,borderColor:'#284237',borderRadius:18,fontSize:16},filter:{paddingHorizontal:13,paddingVertical:12,borderWidth:1,borderColor:'#284237',borderRadius:14},activeFilter:{backgroundColor:'#2dcc98',borderColor:'#2dcc98'},label:{color:'#b7c9bd',fontSize:12,fontWeight:'700'},row:{flexDirection:'row',gap:8},featured:{flexDirection:'row',gap:10},tile:{flex:1,minWidth:0,paddingHorizontal:7,paddingTop:28,paddingBottom:14,borderRadius:18,gap:7,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'#284237'},star:{position:'absolute',right:6,top:4,padding:5},tileSymbol:{fontWeight:'700',color:'#fff',alignSelf:'stretch',textAlign:'center'},tileChange:{fontWeight:'700',fontVariant:['tabular-nums']},oi:{color:'#91a79a',fontSize:10,lineHeight:16},copy:{color:'#91a79a',fontSize:11,lineHeight:18},marketRow:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:14,borderBottomWidth:1,borderBottomColor:'#284237'},symbol:{color:'#fff',fontSize:17,fontWeight:'600'},quote:{alignItems:'flex-end',gap:6},price:{color:'#fff',fontSize:14,fontVariant:['tabular-nums']},error:{color:'#ff9c9c'}});
