import type {Database} from './db.js';
export function notificationInput(input:Record<string,unknown>){
 const pushToken=input.pushToken;if(typeof pushToken!=='string'||!/^Expo(nent)?PushToken\[[A-Za-z0-9_-]+\]$/.test(pushToken)||pushToken.length>200)throw new Error('Invalid notification device token.');
 for(const field of ['news','alerts','digest'])if(typeof input[field]!=='boolean')throw new Error('Choose your notification preferences.');
 return {pushToken,news:input.news as boolean,alerts:input.alerts as boolean,digest:input.digest as boolean};
}
export class MobilePush{
 constructor(private db:Database){}
 async migrate(){await this.db.pool.query(`CREATE TABLE IF NOT EXISTS mobile_push_devices(push_token TEXT PRIMARY KEY,identity_id UUID NOT NULL REFERENCES mobile_identities(id) ON DELETE CASCADE,news BOOLEAN NOT NULL DEFAULT FALSE,alerts BOOLEAN NOT NULL DEFAULT FALSE,digest BOOLEAN NOT NULL DEFAULT FALSE,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),last_sent_at TIMESTAMPTZ,last_news_at TIMESTAMPTZ);
 CREATE TABLE IF NOT EXISTS mobile_push_deliveries(push_token TEXT REFERENCES mobile_push_devices(push_token) ON DELETE CASCADE,item_id TEXT,expo_ticket TEXT,receipt_checked BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(push_token,item_id));`);}
 async preferences(identity:string,pushToken?:string){const r=await this.db.pool.query('SELECT news,alerts,digest FROM mobile_push_devices WHERE identity_id=$1 AND push_token=$2 ORDER BY updated_at DESC LIMIT 1',[identity,pushToken??null]);return r.rows[0]??{news:false,alerts:false,digest:false};}
 async register(identity:string,input:Record<string,unknown>){const p=notificationInput(input);await this.db.pool.query(`INSERT INTO mobile_push_devices(push_token,identity_id,news,alerts,digest) VALUES($1,$2,$3,$4,$5) ON CONFLICT(push_token) DO UPDATE SET identity_id=$2,news=$3,alerts=$4,digest=$5,updated_at=NOW()`,[p.pushToken,identity,p.news,p.alerts,p.digest]);return p;}
 async disable(identity:string,pushToken?:string){await this.db.pool.query(`DELETE FROM mobile_push_devices WHERE identity_id=$1 AND ($2::text IS NULL OR push_token=$2)`,[identity,pushToken??null]);}
 start(){let running=false;const poll=async()=>{if(running)return;running=true;try{await this.digest();await this.receipts();await this.send();}catch{console.warn('Pulse push delivery unavailable; will check again.');}finally{running=false;}};const timer=setInterval(()=>void poll(),60000);timer.unref();void poll();return()=>clearInterval(timer);}
 async digest(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date());if(parts.find(p=>p.type==='hour')?.value!=='08')return;const date=['year','month','day'].map(k=>parts.find(p=>p.type===k)?.value).join('-');const r=await this.db.pool.query(`SELECT title FROM pulse_feed_items WHERE kind='news' AND published_at>NOW()-INTERVAL '24 hours' ORDER BY published_at DESC LIMIT 3`);if(!r.rows.length)return;await this.db.savePulseItem({id:`native-digest:${date}`,kind:'brief',title:'Your daily Pulse digest',body:'Your daily Pulse digest\n\n'+r.rows.map(row=>row.title).join('\n'),sourceName:'Funded Guardian'});}
 async send(){
 // Latest eligible item per device; do not replay the archive when someone opts in.
 const r=await this.db.pool.query(`SELECT d.push_token,p.id,p.kind,p.title,p.source_name FROM mobile_push_devices d JOIN LATERAL(SELECT p.* FROM pulse_feed_items p WHERE p.published_at>d.updated_at AND p.published_at>NOW()-INTERVAL '30 minutes' AND ((p.kind='news' AND d.news AND (d.last_news_at IS NULL OR d.last_news_at<NOW()-INTERVAL '30 minutes')) OR (p.kind='brief' AND d.digest) OR (p.kind NOT IN('news','brief') AND d.alerts)) AND NOT EXISTS(SELECT 1 FROM mobile_push_deliveries x WHERE x.push_token=d.push_token AND x.item_id=p.id) ORDER BY p.published_at DESC LIMIT 1)p ON TRUE WHERE d.last_sent_at IS NULL OR d.last_sent_at<NOW()-INTERVAL '5 minutes' LIMIT 100`);
 for(const item of r.rows){
 const claimed=await this.db.pool.query(`INSERT INTO mobile_push_deliveries(push_token,item_id) VALUES($1,$2) ON CONFLICT DO NOTHING RETURNING item_id`,[item.push_token,item.id]);if(!claimed.rowCount)continue;
 // Claim before sending: an ambiguous network response is never automatically resent.
 try{const response=await fetch('https://exp.host/--/api/v2/push/send',{method:'POST',headers:{'Content-Type':'application/json',...(process.env.EXPO_ACCESS_TOKEN?{Authorization:`Bearer ${process.env.EXPO_ACCESS_TOKEN}`}:{})},signal:AbortSignal.timeout(15000),body:JSON.stringify({to:item.push_token,title:item.kind==='news'?`${item.source_name??'Pulse'} news`:item.title,body:item.kind==='news'?item.title:'Open Pulse for the latest update.',sound:'default',data:{screen:'pulse',itemId:item.id},ttl:1800})});if(!response.ok)throw new Error('Push service rejected request');const value=await response.json() as {data?:{status?:string;id?:string;details?:{error?:string}}};if(value.data?.details?.error==='DeviceNotRegistered'){await this.db.pool.query('DELETE FROM mobile_push_devices WHERE push_token=$1',[item.push_token]);continue;}if(value.data?.status!=='ok')throw new Error('Push ticket rejected');await this.db.pool.query(`UPDATE mobile_push_deliveries SET expo_ticket=$3 WHERE push_token=$1 AND item_id=$2`,[item.push_token,item.id,value.data.id]);await this.db.pool.query(`UPDATE mobile_push_devices SET last_sent_at=NOW(),last_news_at=CASE WHEN $2='news' THEN NOW() ELSE last_news_at END WHERE push_token=$1`,[item.push_token,item.kind]);}catch{console.warn('Pulse push attempt could not be confirmed.');}
 }
 }
 async receipts(){await this.db.pool.query(`DELETE FROM mobile_push_deliveries WHERE created_at<NOW()-INTERVAL '7 days'`);const r=await this.db.pool.query(`SELECT push_token,item_id,expo_ticket FROM mobile_push_deliveries WHERE expo_ticket IS NOT NULL AND NOT receipt_checked AND created_at<NOW()-INTERVAL '15 minutes' ORDER BY created_at LIMIT 100`);if(!r.rows.length)return;const response=await fetch('https://exp.host/--/api/v2/push/getReceipts',{method:'POST',headers:{'Content-Type':'application/json',...(process.env.EXPO_ACCESS_TOKEN?{Authorization:`Bearer ${process.env.EXPO_ACCESS_TOKEN}`}:{})},signal:AbortSignal.timeout(15000),body:JSON.stringify({ids:r.rows.map(row=>row.expo_ticket)})});if(!response.ok)return;const value=await response.json() as {data?:Record<string,{status?:string;details?:{error?:string}}>};for(const row of r.rows){const receipt=value.data?.[row.expo_ticket];if(!receipt)continue;if(receipt.details?.error==='DeviceNotRegistered')await this.db.pool.query('DELETE FROM mobile_push_devices WHERE push_token=$1',[row.push_token]);else await this.db.pool.query('UPDATE mobile_push_deliveries SET receipt_checked=TRUE WHERE push_token=$1 AND item_id=$2',[row.push_token,row.item_id]);}await this.db.pool.query(`DELETE FROM mobile_push_deliveries WHERE created_at<NOW()-INTERVAL '7 days'`);}
}
